// <auto-generated />
using System;
using ELT_Piplene.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELT_Piplene.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250925204634_done")]
    partial class done
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ELT_Piplene.Models.Department", b =>
                {
                    b.Property<int>("Dnum")
                        .HasColumnType("int");

                    b.Property<string>("Dname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hiring_Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager_SSN")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Dnum");

                    b.HasIndex("Manager_SSN");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ELT_Piplene.Models.DepartmentLocation", b =>
                {
                    b.Property<int>("Dnum")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Dnum", "Location");

                    b.ToTable("DepartmentLocations");
                });

            modelBuilder.Entity("ELT_Piplene.Models.Dependent", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ESSN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Birthdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name", "ESSN");

                    b.HasIndex("ESSN");

                    b.ToTable("Dependents");
                });

            modelBuilder.Entity("ELT_Piplene.Models.Employee", b =>
                {
                    b.Property<string>("SSN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Birthdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Dnum")
                        .HasColumnType("int");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Super_SSN")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SSN");

                    b.HasIndex("Dnum");

                    b.HasIndex("Super_SSN");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ELT_Piplene.Models.Employee_Projects", b =>
                {
                    b.Property<string>("ESSN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Pnum")
                        .HasColumnType("int");

                    b.Property<int?>("NumOfHours")
                        .HasColumnType("int");

                    b.HasKey("ESSN", "Pnum");

                    b.HasIndex("Pnum");

                    b.ToTable("EmployeeProjects");
                });

            modelBuilder.Entity("ELT_Piplene.Models.Project", b =>
                {
                    b.Property<int>("Pnum")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Dnum")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pnum");

                    b.HasIndex("Dnum");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ELT_Piplene.Models.Department", b =>
                {
                    b.HasOne("ELT_Piplene.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("Manager_SSN")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ELT_Piplene.Models.DepartmentLocation", b =>
                {
                    b.HasOne("ELT_Piplene.Models.Department", "Department")
                        .WithMany("Locations")
                        .HasForeignKey("Dnum")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ELT_Piplene.Models.Dependent", b =>
                {
                    b.HasOne("ELT_Piplene.Models.Employee", "Employee")
                        .WithMany("Dependents")
                        .HasForeignKey("ESSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ELT_Piplene.Models.Employee", b =>
                {
                    b.HasOne("ELT_Piplene.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("Dnum")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ELT_Piplene.Models.Employee", "Supervisor")
                        .WithMany("Subordinates")
                        .HasForeignKey("Super_SSN")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("ELT_Piplene.Models.Employee_Projects", b =>
                {
                    b.HasOne("ELT_Piplene.Models.Employee", "Employee")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("ESSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELT_Piplene.Models.Project", "Project")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("Pnum")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ELT_Piplene.Models.Project", b =>
                {
                    b.HasOne("ELT_Piplene.Models.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("Dnum")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ELT_Piplene.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Locations");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ELT_Piplene.Models.Employee", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("EmployeeProjects");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("ELT_Piplene.Models.Project", b =>
                {
                    b.Navigation("EmployeeProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
